name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout Source Repository
      - uses: bazel-contrib/setup-bazel@0.13.0
        name: Bazel Setup
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Build
        run: bazel build //...
      - name: Test
        run: bazel test //... --test_summary=detailed
      - if: matrix.os == 'ubuntu-latest'
        uses: jidicula/clang-format-action@v4.15.0
        name: Check Style
        with:
          clang-format-version: "20"
          check-path: "nbsim"
